### ISSUE TITLE
githubリポジトリを管理したい

### ISSUE THREAD

**Issue by daleksprinter** [daleksprinter/dotfiles#4]
現状だとghqコマンドで毎回手打ちしてる
ファイルにgithubリポジトリ書いといて、makeで一発で全部clone
追加もファイルに追加してmake叩くだけ
みたいな管理の仕方をしたい

**Comment by a5ob7r** [comment]
こんなものがあるみたいだけどいかが？

https://github.com/Songmu/ghq-handbook/blob/master/ja/07-bulk-ghq-get.md

**Comment by daleksprinter** [comment]
それっぽいことができたのでclose
